
export namespace Notes {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * a Notes account
  */
 export interface Account {
   /**
    * the name of the account
    */
   name(): string;
   /**
    * the unique identifier of the account
    */
   id(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * a folder containing notes
  */
 export interface Folder {
   /**
    * the name of the folder
    */
   name(): string;
   /**
    * the unique identifier of the folder
    */
   id(): string;
   /**
    * the container of the folder
    */
   container(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * a note in the Notes application
  */
 export interface Note {
   /**
    * the name of the note (normally the first line of the body)
    */
   name(): string;
   /**
    * the unique identifier of the note
    */
   id(): string;
   /**
    * the folder of the note
    */
   container(): any;
   /**
    * the HTML content of the note
    */
   body(): string;
   /**
    * the creation date of the note
    */
   creationDate(): any;
   /**
    * the modification date of the note
    */
   modificationDate(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * an attachment in a note
  */
 export interface Attachment {
   /**
    * the name of the attachment
    */
   name(): string;
   /**
    * the unique identifier of the attachment
    */
   id(): string;
   /**
    * the note containing the attachment
    */
   container(): any;
   /**
    * the content-id URL in the note's HTML
    */
   contentIdentifier(): string;
 }
    
    // CLass Extension
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * the Notes application
  */
 export interface Application {}
    
    // Records

    // Function options

}
export interface Notes extends Notes.Application {
    // Functions

     /**
      * Open a note URL.
      * @param directParameter The URL to be opened.
      * 
      */
     openNoteLocation(directParameter: {}, ): void;
}
