
export namespace Reminders {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * an account in the Notes application
  */
 export interface Account {
   /**
    * the name of the account
    */
   name(): string;
   /**
    * the unique identifier of the account
    */
   id(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * a list in the Reminders application
  */
 export interface List {
   /**
    * the name of the list
    */
   name(): string;
   /**
    * the unique identifier of the list
    */
   id(): string;
   /**
    * the container of the list
    */
   container(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * a reminder in the Reminders application
  */
 export interface Reminder {
   /**
    * the name of the reminder
    */
   name(): string;
   /**
    * the unique identifier of the reminder
    */
   id(): string;
   /**
    * the notes attached to the reminder
    */
   body(): string;
   /**
    * Is the reminder completed?
    */
   completed(): boolean;
   /**
    * the completion date of the reminder
    */
   completionDate(): any;
   /**
    * the container of the reminder
    */
   container(): any;
   /**
    * the creation date of the reminder
    */
   creationDate(): any;
   /**
    * the due date of the reminder
    */
   dueDate(): any;
   /**
    * the modification date of the reminder
    */
   modificationDate(): any;
   /**
    * the remind date of the reminder
    */
   remindMeDate(): any;
   /**
    * the priority of the reminder
    */
   priority(): number;
 }
    
    // CLass Extension
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * the Reminders application
  */
 export interface Application {
   /**
    * the account currently active in the Reminders application
    */
   defaultAccount(): any;
   /**
    * the list currently active in the Reminders application
    */
   defaultList(): any;
 }
    
    // Records

    // Function options


}
export interface Reminders extends Reminders.Application {
    // Functions

     /**
      * Open a Reminder in the UI
      * @param directParameter the Reminders URL
      * 
      */
     getURL(directParameter: string, ): void;

     /**
      * Show an object in the UI
      * @param directParameter The object to be shown
      * @return The object shown.
      */
     show(directParameter: {}, ): void;
}
