
export namespace VoiceOver {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * VoiceOver
  */
 export interface Application {
   /**
    * The VoiceOver cursor
    */
   voCursor(): any;
   /**
    * The VoiceOver commander
    */
   commander(): any;
   /**
    * The mouse cursor
    */
   mouseCursor(): any;
   /**
    * The keyboard cursor
    */
   keyboardCursor(): any;
   /**
    * The VoiceOver caption panel
    */
   captionPanel(): any;
   /**
    * The VoiceOver braille panel
    */
   braillePanel(): any;
   /**
    * The last phrase VoiceOver output
    */
   lastPhrase(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The VoiceOver cursor
  */
 export interface VoCursorObject {
   /**
    * The bounds of the VoiceOver cursor
    */
   bounds(): any;
   /**
    * The text of the item in the VoiceOver cursor
    */
   textUnderCursor(): string;
   /**
    * The magnification factor of the VoiceOver cursor
    */
   magnification(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The VoiceOver commander.
  */
 export interface CommanderObject {}

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The caption panel
  */
 export interface CaptionPanelObject {
   /**
    * The number of rows
    */
   rows(): number;
   /**
    * The size
    */
   size(): number;
   /**
    * The visibility of the panel
    */
   visible(): boolean;
   /**
    * The location of the panel
    */
   position(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The braille panel
  */
 export interface BraillePanelObject {
   /**
    * The size
    */
   size(): number;
   /**
    * The visibility of the panel
    */
   visible(): boolean;
   /**
    * The location of the panel
    */
   position(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The mouse cursor
  */
 export interface MouseCursorObject {
   /**
    * Position of the mouse
    */
   position(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The last phrase outputted
  */
 export interface LastPhraseObject {
   /**
    * The text of the last phrase
    */
   content(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The keyboard cursor
  */
 export interface KeyboardCursorObject {
   /**
    * The bounds of the keyboard cursor
    */
   bounds(): any;
   /**
    * The text of the item in the keyboard cursor
    */
   textUnderCursor(): string;
 }
    
    // CLass Extension
    
    // Records

    // Function options


    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface ClickOptionalParameter {
      /**
       * Mouse button to click
       */
      with?: any;
    }






    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface MoveOptionalParameter {
      /**
       * The place to move to
       */
      to?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface OutputOptionalParameter {
      /**
       * Type of reading
       */
      with?: any;
    }





}
export interface VoiceOver extends VoiceOver.Application {
    // Functions

     /**
      * undefined
      * @param directParameter The English name of the VoiceOver command to perform
      * 
      */
     performCommand(directParameter: string, ): void;

     /**
      * Takes a screenshot of the VO cursor and returns the path to the file
      * @param directParameter the vo cursor object to grab
      * @return the path to the screenshot
      */
     grabScreenshot(directParameter: VoiceOver.VoCursorObject, ): string;

     /**
      * undefined
      * @param directParameter Number of times to click
      * @param option
      * 
      */
     click(directParameter?: {}, option?: VoiceOver.ClickOptionalParameter): void;

     /**
      * undefined

      * 
      */
     quit(): void;

     /**
      * undefined
      * @param directParameter The mouse cursor object
      * 
      */
     press(directParameter: VoiceOver.MouseCursorObject, ): void;

     /**
      * undefined
      * @param directParameter The mouse cursor object
      * 
      */
     release(directParameter: VoiceOver.MouseCursorObject, ): void;

     /**
      * undefined
      * @param directParameter The vo cursor object
      * 
      */
     performAction(directParameter: VoiceOver.VoCursorObject, ): void;

     /**
      * undefined
      * @param directParameter The vo cursor object
      * 
      */
     select(directParameter: VoiceOver.VoCursorObject, ): void;

     /**
      * Move the vo cursor to a new location.
      * @param directParameter The direction to move in.
      * @param option
      * 
      */
     move(directParameter?: {}, option?: VoiceOver.MoveOptionalParameter): void;

     /**
      * Output
      * @param directParameter item to be outputted
      * @param option
      * 
      */
     output(directParameter?: {}, option?: VoiceOver.OutputOptionalParameter): void;

     /**
      * undefined
      * @param directParameter the item to open
      * 
      */
     open(directParameter: {}, ): void;

     /**
      * Closes open menus

      * 
      */
     closeMenu(): void;

     /**
      * Save last phrase
      * @param directParameter The last phrase object
      * 
      */
     save(directParameter: VoiceOver.LastPhraseObject, ): void;

     /**
      * Copy last phrase to pasteboard
      * @param directParameter The last phrase object
      * 
      */
     copyToPasteboard(directParameter: VoiceOver.LastPhraseObject, ): void;
}
