name: test
on: [push, pull_request]
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [ 20, 22 ]
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install && yarn bootstrap
      - name: Test
        run: yarn test
